# Generated by Django 4.0 on 2021-12-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesage',
            name='date_message',
        ),
        migrations.RemoveField(
            model_name='mesage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='mesage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='mesage',
            name='text',
        ),
        migrations.AddField(
            model_name='mesage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mesage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to='auth.user'),
        ),
        migrations.AddField(
            model_name='mesage',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mesage',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mesage',
            name='viewers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewers', to='auth.user'),
        ),
    ]
