# Generated by Django 4.0 on 2021-12-29 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0002_remove_mesage_date_message_remove_mesage_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesage',
            name='viewers',
        ),
        migrations.AddField(
            model_name='mesage',
            name='viewers',
            field=models.ManyToManyField(null=True, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
